name: Mirror to Codeberg

on:
  push:
  pull_request:

jobs:
  mirror:
    name: Mirror to Codeberg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Load ssh key
        env: 
          SSH_KEY: ${{ secrets.CODEBERG_SSH_KEY }}
        run: |
          umask 066
          echo "$SSH_KEY" > ~/codeberg_key

      - name: Add Codeberg to known hosts
        run: echo "codeberg.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIVIC02vnjFyL+I4RHfvIGNtOgJMe769VTF1VR4EB3ZB" > ~/known_hosts

      - name: Push to Codeberg
        env:
          BRANCH: ${{ github.event_name == 'pull_request' && format('pull/{0}', github.event.number) || github.ref_name }}
          GIT_SSH_COMMAND: 'ssh -i ~/codeberg_key -o IdentitiesOnly=yes -o GlobalKnownHostsFile=~/known_hosts -o StrictHostKeyChecking=yes'
        run: git push --force git@codeberg.org:Eskaan/leftwm-mirror-testing.git HEAD:$BRANCH
