name: Mirror to Codeberg

on:
  push:
  pull_request:

jobs:
  mirror:
    name: Mirror to Codeberg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load ssh key
        env: 
          SSH_KEY: ${{ secrets.CODEBERG_SSH_KEY }}
        run: echo "$SSH_KEY" > /etc/ssh/codeberg_key

      - name: Add Codeberg to known hosts
        run: echo "codeberg.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIVIC02vnjFyL+I4RHfvIGNtOgJMe769VTF1VR4EB3ZB" > /etc/ssh/known_hosts
          
      - name: Push repo
        env:
          GIT_SSH_COMMAND: 'ssh -i /etc/ssh/codeberg_key -o IdentitiesOnly=yes -o  -o StrictHostKeyChecking=yes'
        run: git push --mirror git@codeberg.org:Eskaan/leftwm-mirror-testing.git
